[package]
name = "cuid"
version = "1.2.0"
license = "MIT"
edition = "2021"
authors = ["Matthew Planchard <msplanchard@gmail.com>"]
description = "An ipmlementation of CUID protocol in rust"
documentation = "https://docs.rs/cuid/latest/cuid/"
homepage = "https://github.com/mplanchard/cuid-rust"
repository = "https://github.com/mplanchard/cuid-rust"
exclude = [".github/**", ".vscode/**"]

[dev-dependencies]
criterion = "~0.3"

[dependencies]
arraystring = "0.3.0"
hostname = "~0.3.0"
once_cell = "1.9.0"
rand = "~0.8.0"

[lib]
name = "cuid"
path = "src/lib.rs"

[[bin]]
name = "cuid"
path = "src/bin.rs"

[[bench]]
name = "cuid"
harness = false
