[workspace]
members = [ "crates/*" ]

[workspace.package]
edition = "2021"
authors = [ "Matthew Planchard <msplanchard@gmail.com>" ]
license = "MIT"
homepage = "https://github.com/mplanchard/cuid-rust"
repository = "https://github.com/mplanchard/cuid-rust"
