[toolchain]
channel = "stable"
components = [
    "clippy-preview",
    "llvm-tools-preview",
    "rustfmt",
    "rust-src",
    "rust-std",
]
targets = [
    "wasm32-unknown-unknown",
    "wasm32-wasi",
    "wasm32-unknown-emscripten",
]
