name: "CI"
on: [push, pull_request]

jobs:
  test:
    name: "Test"
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        toolchain: ["stable", "beta", "nightly"]
        test_args:
          - "-p cuid"
          - "-p cuid -- collisions::test --ignored"
          - "-p cuid -- collisions::single_thread --ignored --test-threads 1"
          - "-p cuid2"
          - "-p cuid2 -- --ignored test::collisions"
          - "-p cuid2 -- --ignored test::distribution"

    runs-on: "${{ matrix.os }}"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions-rs/toolchain@v1"
        with:
          profile: "minimal"
          toolchain: "${{ matrix.toolchain }}"
          override: true
      - uses: "actions-rs/cargo@v1"
        with:
          command: "test"
          args: "${{ matrix.test_args }}"

  audit:
    name: "Audit"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions-rs/audit-check@v1"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

  # Ensure builds succeed for WASM targets
  wasm:
    name: "WASM Builds"
    strategy:
      matrix:
        target:
          - "wasm32-unknown-unknown"
          - "wasm32-wasi"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions-rs/cargo@v1"
        with:
          command: "build"
          args: "--target ${{ matrix.target }}"

  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          override: true
          components: clippy
      - uses: "actions-rs/cargo@v1"
        with:
          command: "clippy"
          args: "--all-features -- -D warnings"

  lint-release:
    name: "Lint Release Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          override: true
          components: clippy
      - uses: "actions-rs/cargo@v1"
        with:
          command: "clippy"
          args: "--release --all-features -- -D warnings"

  fmt:
    name: "Format"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions-rs/toolchain@v1"
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true
      - uses: "actions-rs/cargo@v1"
        with:
          command: "fmt"
          args: "--all -- --check"

  docs:
    name: "Docs"
    runs-on: "ubuntu-latest"
    env:
        RUSTDOCFLAGS: "-D warnings"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions-rs/toolchain@v1"
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true
      - uses: "actions-rs/cargo@v1"
        with:
          command: "doc"
          args: "--no-deps"

  Verify:
    name: "Verify"
    runs-on: "ubuntu-latest"
    needs:
      - "docs"
      - "fmt"
      - "test"
      - "lint"
      - "lint-release"
      - "audit"
      - "wasm"
    steps:
      - run: "echo 'All pre-commit checks passed!'"
