name: "CI"
on: [push, pull_request]

jobs:
  test:
    name: "Test"
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        toolchain: ["stable", "beta", "nightly"]
        test_args:
          - "-p cuid"
          - "-p cuid -- collisions::test --ignored"
          - "-p cuid -- collisions::single_thread --ignored --test-threads 1"
          - "-p cuid2"
          - "-p cuid2 -- --ignored test::collisions"
          - "-p cuid2 -- --ignored test::distribution"

    runs-on: "${{ matrix.os }}"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions-rs/toolchain@v1"
        with:
          profile: "minimal"
          toolchain: "${{ matrix.toolchain }}"
          override: true
      - uses: "actions-rs/cargo@v1"
        with:
          command: "test"
          args: "${{ matrix.test_args }}"

  audit:
    name: "Audit"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions-rs/audit-check@v1"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          override: true
          components: clippy
      - uses: "actions-rs/cargo@v1"
        with:
          command: "clippy"
          args: "--all-features -- -D warnings"

  fmt:
    name: "Format"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions-rs/toolchain@v1"
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true
      - uses: "actions-rs/cargo@v1"
        with:
          command: "fmt"
          args: "--all -- --check"

  Verify:
    name: "Verify"
    runs-on: "ubuntu-latest"
    needs:
      - "fmt"
      - "test"
      - "lint"
      - "audit"
    steps:
      - run: "echo 'All pre-commit checks passed!'"
